import Head from "next/head";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>TuniBest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-secondary">Home Page</div>
    </div>
  );
}
